@echo off
echo Starting EventHive with Socket.IO...
echo.

echo Starting Socket.IO server...
start /b "Socket.IO Server" node socket-server.js

echo Waiting for Socket.IO server to start...
timeout /t 3 /nobreak > nul

echo Starting Next.js development server...
npm run dev
